### ISSUE TITLE
Use the term "remake" instead of "port" in documentation

### ISSUE THREAD

**Issue by ks202005** [Rubberduckycooly/Sonic-CD-11-Decompilation#1]
The Christian Whitehead Retro Engine versions of Sonic games (including CD) are remakes and none of them share source code with the original Sega Mega Drive/Mega CD releases. This means that they are not ports. There was a true source port of Sonic CD to PC made in 1996. In the documentation, it's confusing to have the word "port" used several times to describe the 2011 remake because there is a real port that used an unrelated code base.

**Comment by Rubberduckycooly** [comment]
oh yeah give me a sec to change that hold on
