### ISSUE TITLE
The Special Stages appear smaller than the rest of the game with Integer Scaling Enabled

### ISSUE THREAD

**Issue by Gagert** [Rubberduckycooly/Sonic-CD-11-Decompilation#108]
I recently downloaded Release v1.1.2 of this Sonic CD decompilation for my Windows 10 PC. I use the files within the Software renderer folder, SW, and use the following settings under [window] in settings.ini:

Fullscreen=true
Borderless=false
VSync=true
ScalingMode=1
WindowScale=2
ScreenWidth=400
RefreshRate=60
DimLimit=300

By using ScalingMode 1, I use the newly implemented Integer Scaling, which is my own personal preference when playing games with pixel graphics. The menus and the levels itself in the game works as intended, but somehow the screen area becomes even smaller than usual as soon as I enter the Special Stages. It's as if there's some lines of code missing in this decompilation to make the Integer Scaling work as intended during Special Stages.

One way to check if this works or not fast, is to just wait during the Sonic title screen for the prerecorded gameplay demos to appear, and the second- or the third of those demos is the Special Stages.

Edit: After looking more into this, it seems like the Special Stages in the 2011 release of Sonic CD runs in a way higher resolution than the rest of the game (thereby the differences in screen real-estate while using Integer Scaling when comparing the Special Stages to the rest of the game). By using ScalingMode=0 instead, Nearest Neighbor Scaling instead of Integer Scaling, it was easy to see how sharp the Special Stages are compared to the rest of the game.

Maybe an extra option in the settings.ini could be added to somehow force the Special Stages to use the same Integer Scaling factor as the rest of the game?

**Comment by TheAgamer554** [comment]
set UseHQModes=false so that special stages run in 240p instead of 480p and the scaling is consistent

**Comment by Gagert** [comment]
Thanks for the reply, that worked!!

My mistake for creating this thread, this was an user error (as in me).
