### ISSUE TITLE
Still crashing in special stage 5. But...

### ISSUE THREAD

**Issue by jkveri2812** [Rubberduckycooly/Sonic-CD-11-Decompilation#117]
Before the new update, there was an issue when, in special stage 5, the game crashed, no matter what.

In the latest version you can play normally, but if you run out of time, instead of showing the score screen, the game crashes.

BUT, it doesn't ALWAYS happen, because I've tested using the dev menu in the stage select, with both Sonic and Tails, and it doesn't happen in the at least four times I've tested it. So, I was thinking this could be "exclusive" of the game itself, not of the stage select. 
I don't know if I made myself understand.

**Comment by Tadpole21** [comment]
I'm on the latest version of the game and I crash on stage 5 if I turn right. It looks like you only crash if you run out of time. Is there something you did to get it to work?

**Comment by jkveri2812** [comment]
> I'm on the latest version of the game and I crash on stage 5 if I turn right. It looks like you only crash if you run out of time. Is there something you did to get it to work?

I fell on the water when I had like 10 seconds left, and obviously, I ran out of time, and then the sky went crazy, and the game crashed.
