### ISSUE TITLE
Bugs with Special Stages with DevMenu disabled

### ISSUE THREAD

**Issue by ViperAcidZX** [Rubberduckycooly/Sonic-CD-11-Decompilation#119]
I'm seeing some weird bugs with the Special Stages with the decompilation. First, the music does not pause when pausing the game with the Start button, it continues to play no matter what, and second, when _UseHQModes_ is set to true, it causes the floor to glitch out as shown in this screenshot below.

![soniccd-2021_06_28_11-49-40](https://user-images.githubusercontent.com/19318128/123666634-64a77980-d807-11eb-9526-ef4b95e8d7da.png)
Disabling UseHQModes fixes the Special Stage floor going pink but game's music still runs when the game is paused.

This issue occurred when using the Steam RSDK data files and it happened in newer builds of the decomp, Sonic CD Restored, and an executable I just compiled today. Here's a log file I got from the new executable I compiled with the instructions on the frontpage hoping it help that it might help with this bug.

[log.txt](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/files/6727631/log.txt)

**Follow-up report:** Okay I found out the cause seem to be having the Touch UI controls enabled with UseHQModes enabled since they where both activated by default when generating a new settings.ini file.

![soniccd-2021_06_28_20-47-35](https://user-images.githubusercontent.com/19318128/123721388-3a2fdd80-d854-11eb-980e-904b1217ccfd.png)
Strangely turning the touch UI off seem to be working as I was able to click around the upper right corner of the screen and it paused the game, and pressing Enter didn't work to pause the game.

**Another follow report:** Okay now it appears that the bug shown in the first screenshot always happen if the Dev Menu is disabled.

**Comment by cheatfreak47** [comment]
Confirming this issue as well. Ran into it myself independently while tinkering with modding Special Stage scripts.

**Comment by Leonx254** [comment]
This issue has been fixed in the latest commit
