### ISSUE TITLE
How to get the assets from APK?

### ISSUE THREAD

**Issue by ZikZakFR** [Rubberduckycooly/Sonic-CD-11-Decompilation#12]
The source compiles flawlessly on Linux but the documentation about what to do next is lacking.
The binary doesn't have any help either.

I extracted the APK from my old smartphone then decompressed it but apart from an Asset folder I can't tell what to keep and use.
I tried launching the binary from many places to no avail, not even an error message.

Can you update the README with explanation for each version?

**Comment by Idah00** [comment]
The bare minimum that is required for the game to be able boot up is to have "Data.rsdk" in the same folder as the executable, did you find this file in the Android apk?

**Comment by Rubberduckycooly** [comment]
the android APK is very weird with where the data.rsdk file is, im not even sure myself where the data.rsdk file is, if possible I'd recommend using the steam version since it has an easier to access data.rsdk file

**Comment by ChrisHighwind** [comment]
The Android version's data.rsdk is hidden in plain sight, in a sense.
![Screenshot_20210104-210907_X-plore](https://user-images.githubusercontent.com/10728382/104257392-54633400-544b-11eb-8ae9-e932dbafb3b9.jpg)
You'll need to look at Sonic CD's obb folder, and you'll find two .obbs. The one with "main" in the title you can rename to a .zip and it contains the opening, endings, and pencil video. The one with "patch" in the title is different. I didn't notice this until Sappharad asked about the beginning hex offset in it, but the .obb with "patch" in the title is actually the Data.rsdk, and if you rename it to such, the decomp accepts it (at least Xeeynamo's Vita port does, anyway)

**Comment by Rubberduckycooly** [comment]
checked myself on an older (pre sega forever) version and confirmed this is still the case

**Comment by ZikZakFR** [comment]
Worked almost perfectly, at least it answered my question "where to find the assets?".
Looks like the video are expected to be somewhere else ore even in another format (ogg theora?).
But that would be another issue to open.
