### ISSUE TITLE
Prebuilt MacOS Port Breaks

### ISSUE THREAD

**Issue by ThomasfanSQB** [Rubberduckycooly/Sonic-CD-11-Decompilation#123]
Look here first: https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/issues/248

The MacOS port breaks when you put the Data.rsdk file in app/Contents/Resources. It's so dumb.
Also, why do we have to build our own app to get this running? Why can't it be rebuilt?
Hopefully, you can fix these.

P.S. Can you ask heyjoeway to make a Switch port of this, please?

**Comment by MegAmi24** [comment]
Neither of the decomp devs have means of compiling a signed build of the decomps for mac.
