### ISSUE TITLE
How do I build for UWP?

### ISSUE THREAD

**Issue by coolpringles** [Rubberduckycooly/Sonic-CD-11-Decompilation#131]
I open the project in VS2019 and SDL2 builds fine, but when it comes to RSDK, it's missing glew.h.

I get it to include it but it still throws errors at me about syntax errors in random places.

I'm really out of my depth here (my depth is very basic python lol) so any help is really appreciated!

**Comment by mediaexplorer74** [comment]
> I open the project in VS2019 and SDL2 builds fine, but when it comes to RSDK, it's missing glew.h.
> 
> I get it to include it but it still throws errors at me about syntax errors in random places.
> 
> I'm really out of my depth here (my depth is very basic python lol) so any help is really appreciated!

I tried to build for UWP. No success too. The developers use bad practice "not include all dependencies" . So sad  (
