### ISSUE TITLE
macOS: Hi-res mode incorrectly scaled

### ISSUE THREAD

**Issue by SupakugaiGames** [Rubberduckycooly/Sonic-CD-11-Decompilation#133]
In the current state of the decomp ([86f916c](https://github.com/SupakugaiGames/Sonic-CD-11-Decompilation/commit/86f916cf5361f89ec28eccc665bdeb913e16f922) at the time of writing), the macOS version of RSDKv3 starts up with a blank screen and does nothing. No mod menu, no title screen, no music or sound, no inputs accepted, no anything. The game just doesn't start up correctly. I forked the project and added some debug prints to determine if the engine was even starting up, and from what I can gather, it is. Yet the game just doesn't begin. Running macOS 11.6 on an M1 MacBook Air, and I tested both ARM64 and x86_64 builds. No results. The game crashes as expected if Data.rsdk is not present, but when it is, it just does this:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/77683570/137894859-77360b32-c872-415c-aac4-f6b617ffce47.png">
The settings.ini file is also being overwritten each launch, as mentioned in #124. My RSDK file is fine, as it worked in previous versions of the decomp. So I'm racking my brain here trying to figure out what's going on. Does anyone know what the problem is?

**Comment by SupakugaiGames** [comment]
Because the settings.ini keeps getting overwritten, I edited the code to force a log just now. It didn't write to a file but it wrote in my Xcode window. Here's what I got:

`ERROR: Couldn't open file '/Users/Me/Library/Application Support/RSDKv3/settings.ini'!
Couldn't load file 'Data/Scripts/ByteCode/GlobalCode.bin'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Scripts/ByteCode/GS000.bin'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/mods/Time Travel Overhaul/Data/Game/GameConfig.bin'
2021-10-20 23:17:24.696605+0700 RSDKv3[48814:12864348] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000008facc0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2021-10-20 23:17:25.056497+0700 RSDKv3[48814:12864348] Metal API Validation Enabled
2021-10-20 23:17:25.084976+0700 RSDKv3[48814:12864348] +[MTLIOAccelDevice registerDevices]: Zero Metal services found
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Jump.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Ring.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Ring.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Skidding.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/LoseRings.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Hurt.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Charge.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Release.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Destroy.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/LampPost.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/BlueShield.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Spring.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Future.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Past.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/TimeWarp.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/SignPost.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/ScoreAdd.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/ScoreTotal.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/SpecialRing.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/SpecialWarp.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/1Up.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Achievement.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Explosion.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/MenuButton.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Flying.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Tired.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/OuttaHere.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Global/Select.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Palettes/MasterPalette.act'
Set Object (0) name to: Blank Object
Loading Scene Presentation Stages - TITLE SCREEN
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Palettes/MasterPalette.act'
Set Object (0) name to: Blank Object
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Stages/Title/StageConfig.bin'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Stages/Title/StageConfig.bin'
Set Object (1) name to: Sega
Set Object (2) name to: Sonic
Set Object (3) name to: Logo
Set Object (4) name to: Background
Set Object (5) name to: Clouds
Set Object (6) name to: Touch Start
Set Object (7) name to: CWLogo
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Scripts/ByteCode/PS000.bin'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/SoundFX/Stage/Sega.wav'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Stages/Title/16x16Tiles.gif'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Stages/Title/16x16Tiles.gif'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Stages/Title/CollisionMasks.bin'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Stages/Title/Backgrounds.bin'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Stages/Title/128x128Tiles.bin'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Stages/Title/Act1.bin'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Sprites/Title/Title.gif'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Sprites/Title/Clouds.gif'
Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Sprites/Title/CWLogo.gif'`

What it then does is continually print
`Callback: Display Logos`
until I quit the program. Nothing appears onscreen.

When I set the default starting scene to 1, it continually loops `Loaded File '/Users/Me/Library/Application Support/RSDKv3/Data/Music/JP/SpecialStage.ogg'` and doesn't display anything either.

**Comment by MGRich** [comment]
That's _really_ weird. Could you try placing a breakpoint in `Reader.cpp:226` once it starts repeating and show the stack trace? I don't use XCode myself (I don't manage Mac development, RDC does,) so sorry if placing breakpoints mid-run is impossible.

**Comment by MGRich** [comment]
`pathBuffer` should _not_ look like that. This is a great find; I'll forward this issue to RDC.

**Comment by SupakugaiGames** [comment]
I didn't see a variable for settings.ini to toggle forced scripts, so I enabled it in the code. The game loads the scripts, but I get the same result. Empty screen, looping text in the log.

**Comment by MGRich** [comment]
For future reference, the option is `TxtScripts` near the top, IIRC. Still, extremely weird that it just is not successfully loading them. I'll ask around in REMS if someone can test on a Mac as well, but for now I don't have any other leads.

**Comment by MegAmi24** [comment]
Should be fixed in `1960ecb`
