### ISSUE TITLE
Playable characters not rendering in regular stages

### ISSUE THREAD

**Issue by Idah00** [Rubberduckycooly/Sonic-CD-11-Decompilation#14]
I am using Manjaro ARM on my Pinebook Pro, I installed the required libraries and compiled from current git and the game seems to work fine except that  playable characters do not render correctly in regular stages...

I enabled the dev menu and when I choose Tails, I can see his tails but only when he's in idle and jumping position, I also accessed special stages through dev menu and characters render correctly there...

I previously had issues with certain games using mesa-git so I reverted to normal release mesa before creating this entry, the problem is all the same...

I hope you can solve the issue, if you need me to do anything, I'll gladly oblige...

**Comment by Clownacy** [comment]
This is just a guess, but `char` is unsigned by default on ARM unlike on x86, so maybe that has something to do with it? [This variable](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/blob/master/SonicCDDecomp/Animation.cpp#L70) looks suspicious: what if you explicitly made it `signed char`?

**Comment by Idah00** [comment]
> This is just a guess, but `char` is unsigned by default on ARM unlike on x86, so maybe that has something to do with it? [This variable](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/blob/master/SonicCDDecomp/Animation.cpp#L70) looks suspicious: what if you explicitly made it `signed char`?
> 
> EDIT: Whoops, I just realised I could test it myself on x86 by setting it to `unsigned char` and checking if it results in the same bug. It does, so I guess this is the cause of the problem.

Thanks for your quick reply, I edited the file to mark the char as "signed char" and rebuilt the game and it now works, very efficient troubleshooting you did there ;)
