### ISSUE TITLE
Intro Movie not playing/Exit Game option only works in dev menu, not game menu

### ISSUE THREAD

**Issue by bladehorton** [Rubberduckycooly/Sonic-CD-11-Decompilation#143]
Yeah, the title. Is there an extra file required for the intro movie? Because when I click on it, the menu music stops, but nothing plays.

**Comment by MegAmi24** [comment]
Make sure you're using the video files from the Steam version. Also, can you clarify what's happening with the Exit Game button?

**Comment by bladehorton** [comment]
Basically, it does nothing. I click it, the little popup asking if I want to exit, when I click yes the title screen reloads. music and all

**Comment by MegAmi24** [comment]
This is a known issue that doesn't any solutions outside of using mods such as [this one](https://gamebanana.com/mods/50093).
