### ISSUE TITLE
Latest commit does not compile

### ISSUE THREAD

**Issue by nor2101** [Rubberduckycooly/Sonic-CD-11-Decompilation#144]
The [latest commit](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/commit/8ae09f5222243fed7f300a5861e42ea72323cc8b) does not compile under Linux

**Comment by MegAmi24** [comment]
Known issue, we're working on it

**Comment by MegAmi24** [comment]
Should be fixed now

**Comment by nor2101** [comment]
> Should be fixed now

Can confirm! It compiles just fine under Pop!_OS 21.10
