### ISSUE TITLE
Did there’s an a way to extract a patch obb on android without root?

### ISSUE THREAD

**Issue by cicinwad** [Rubberduckycooly/Sonic-CD-11-Decompilation#147]
I’m not sure if I can extract the patch obb because it’s a data rsdk, can I do it on android without root?, plz

**Comment by cicinwad** [comment]
Thanks, now can I extract it on android?!

**Comment by MegAmi24** [comment]
If you mean unpacking the file's contents, no.
By the way, this issue isn't related to the decomp.

**Comment by cicinwad** [comment]
Ok

**Comment by cicinwad** [comment]
But what in the name?!, how did tod put files inside the data.rsdk on android?! [https://youtu.be/nQ3o6zq5cm8](url)

**Comment by MegAmi24** [comment]
You don't.

**Comment by cicinwad** [comment]
I didn't say I was going to put files inside the data.rsdk on android, it was tod, he is the one who did it!

**Comment by MegAmi24** [comment]
If you're using the decomp, there's no reason to do that. There's a mod loader.
