### ISSUE TITLE
I can't use JP soundtrack

### ISSUE THREAD

**Issue by Gr33nEyes** [Rubberduckycooly/Sonic-CD-11-Decompilation#148]
JP OST doesn't work, menu is silent

**Comment by MegAmi24** [comment]
Are you using any mods?

**Comment by Gr33nEyes** [comment]
Vanilla version

**Comment by MegAmi24** [comment]
So the US soundtrack works fine?

**Comment by Gr33nEyes** [comment]
I got this bug, because I extracted RSDK files into my installation directory
