### ISSUE TITLE
[ARM LINUX] Can't jump from floating platforms

### ISSUE THREAD

**Issue by Idah00** [Rubberduckycooly/Sonic-CD-11-Decompilation#15]
So after compiling the game to work on ARM Linux (Manjaro on the PineBook Pro to be exact) I head up into the game but I figured something strange...
Whenever I land on a floating platform I can move in all directions and even make a spin dash and and a CD dash but I can not jump, this happens on floating platforms and also some of the first platforms you encounter in plamtree panic, including the very first one, I guess they are registered in the game in the same manner as the floating ones if I should take a guess...

Do you have any idea what could cause such a weired issue?

**Comment by Rubberduckycooly** [comment]
is there a specific stage that it happens on? since it'll be easier to debug if I can replicate the issue exactly

**Comment by Idah00** [comment]
As I said, it happens in Palmtree Panic, Stage 1A, first platform you ever encounter.

I have roamed around a few other stages and it does not seem to happen there...

**Comment by Idah00** [comment]
Latest code revisions has solved this issue, thanks for your hardwork :+1:
