### ISSUE TITLE
The source code at this repo is not full

### ISSUE THREAD

**Issue by mediaexplorer74** [Rubberduckycooly/Sonic-CD-11-Decompilation#150]
Hi, developers!

I have no success on building the RSDKv3UWP solution.

Please share the whole set of files (/dependencies/all/theora,  /dependencies/all/ogg, ...vorbis, etc. )

Or provide the git command for doing whole clone (with sub-modules)

Best,
[m][e]

**Comment by MegAmi24** [comment]
Please read dependencies.txt in dependencies/win-uwp.

**Comment by mediaexplorer74** [comment]
> MegAmi24

Hi, [MegAmi24](https://github.com/MegAmi24).
Thank you.  Seems I need to download the whole SDL2 and retarget libvorbis,libogg,and libtheora 
(My target is ARM...)
