### ISSUE TITLE
No music in ending cutscene

### ISSUE THREAD

**Issue by Zarazek2000** [Rubberduckycooly/Sonic-CD-11-Decompilation#153]
For some reason in the newest version of the decompilation when I beat a game as Sonic, the ending cutscene (no matter if it is a bad or good future ending) is playing without any music in both JP and US soundtrack. What is worth adding that when I beat game as a Tails, his version of credits has music. In all of older versions of decompilation music was there, but not in 1.3.0. Any ideas?

**Comment by MegAmi24** [comment]
Fixed in master
