### ISSUE TITLE
No way to play, can't find the RSDK file in the APK

### ISSUE THREAD

**Issue by TsukiZero** [Rubberduckycooly/Sonic-CD-11-Decompilation#157]
Are you sure you aren't leaving some info out? I got the recent Sonic_CD_Base.APK right out of my phone, but can't use it with this decomp.

**Comment by MegAmi24** [comment]
It's not in the APK, read this tutorial https://gamebanana.com/tuts/14942

**Comment by TsukiZero** [comment]
It would be a good idea to note that in the Readme.
