### ISSUE TITLE
Major graphical issue throughout whole game

### ISSUE THREAD

**Issue by LakituDude** [Rubberduckycooly/Sonic-CD-11-Decompilation#158]
As the title say
![Screenshot 2022-05-03 164253](https://user-images.githubusercontent.com/104869852/166571386-4371b97d-2e11-4e25-83be-3bc8cef54b60.png)
s

**Comment by MegAmi24** [comment]
Try updating your graphics drivers

**Comment by Leonx254** [comment]
Closing this since is related to faulty intel HD drivers and not the decomp itself.
