### ISSUE TITLE
[ARM LINUX] Enterring a pipe tunnel usually pushes me back 

### ISSUE THREAD

**Issue by Idah00** [Rubberduckycooly/Sonic-CD-11-Decompilation#16]
So I've noticed another weird issue during my testing of the ARM Linux version on my Manjaro PineBook Pro. 

It seems that pipe tunnels are pushing back instead of making me follow their course, this happens in Palmtree Panic Zone 1 A in the first pipe tunnel you encounter but even easier, you'll be forced to see it in Chaos Collision Zone 1 A as it is really the only to go after Metal Sonic grabs Amy...

**Comment by Rubberduckycooly** [comment]
just to confirm, you're compiling with `char` as an signed type yeah? because based on previous issues it looks like you had `char` as an unsigned type, meaning stuff like collision which needs to store negative values, will break

**Comment by Rubberduckycooly** [comment]
regardless, I have made a push to master that adds explicit signedness on chars that need to be signed, so your issue may be fixed now?

**Comment by Idah00** [comment]
I was compiling with char as a signed type but even that way it didn't work, having char as a signed type would only solve characters not showing up properly...

It seems that your latest additions to the code have solved all the issues I had, pipes do work properly and jumping from certain platform works as well, I'll do a playthrough of the game and if I encounter issues I'll report them but I suspect it is now ready to operate on arm hardware...

**Comment by Rubberduckycooly** [comment]
alright, sweet! let me know if you find anymore bugs
