### ISSUE TITLE
Hardware Renderer error on mobile

### ISSUE THREAD

**Issue by LanceReborn** [Rubberduckycooly/Sonic-CD-11-Decompilation#161]
I have tested this with the latest compile version.
When putting Hardware Renderer in true, the main menu doesn't render correctly (everything is invisible except the background).
I would put in false but the problem is that special stages run painfully slow.

**Comment by SeongGino** [comment]
This is actually an error across platforms when using **Mobile** `data.rsdk` (Linux_x64 here):
![2022_05-07 17-26-53  Sonic CD](https://user-images.githubusercontent.com/7321839/167272358-b2174119-ee29-45db-bf87-b109ac0ca58c.png)

The hardware renderer is missing palettes (readme) and has bad mips in special stages anyways, so the benefits sort of get cancelled out.
![Screenshot_20220507-172643](https://user-images.githubusercontent.com/7321839/167272473-c4c171d8-375c-4bba-80f4-03f36fcebfc4.png)


If you need to use the hardware renderer, the PC/Steam data file renders menus fine with HW, but breaks special stages.
![Screenshot_20220507-172535](https://user-images.githubusercontent.com/7321839/167272455-4956b76f-1899-4c2c-82c1-474874c777e0.png)

Android device in question here is a Retroid Pocket 2+, which can run SCD fine with the software renderer.

**Comment by MegAmi24** [comment]
You're supposed to use software rendering with the Steam RSDK and hardware rendering with the mobile RSDK.

**Comment by MegAmi24** [comment]
menu should be fixed with ``[4aea86f](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/commit/4aea86fdf79099c9c45998fcb83c51455d18f4db)``

**Comment by Leonx254** [comment]
closing issue since it has been fixed back in october
