### ISSUE TITLE
Idle screen dimming not functioning properly in scenes with 3d layers

### ISSUE THREAD

**Issue by Lavesiime** [Rubberduckycooly/Sonic-CD-11-Decompilation#164]
Whenever the game has a 3d layer active, the screen dimming only applies to the top 132 pixels of the screen, leaving the remaining 108 pixels undimmed.

![unknown](https://user-images.githubusercontent.com/70488825/168187720-d99c90a9-0a85-43ac-b398-1b5ec4018bd4.png)

This isn't to be confused with the dimming only the 2d parts of the game, as in the image above, it can be seen that some of the stage's water is dimmed along with the 2d layer behind it. Additionally, the dimmed area is always 132 pixels tall, regardless of how high or low the 3d layer's position actually is on the screen. Also, I am claiming that it is only happening with 3d layers active because no such similar dimming oddity occurs in places like Stardust Speedway Zone or the title screen, where 3d is used via objects and script-managed vertexes instead, where there are no actual 3d layer types.

I should add, too, that this doesn't appear to happen at all in the RSDKv4 decompilation. Places like the Sonic 2 Special Stage or either 2013 game's Level Selects (which have a 3d layer as their background) work fine, so this appears to apply to this RSDKv3 decompilation only.

**Comment by Rubberduckycooly** [comment]
this one is a bit of a pain to deal with, for now I've just disabled screen dim when "drawGFXHQ" is enabled. Maybe one day I'll make a "better" solution

The thing about it not happening in v4 is this is since it uses the "3DFloor" layer mode, and that's broken due to the funky 2x stuff it does. the 3DScene stuff is workin as intended
