### ISSUE TITLE
Screen dimming not pausing with frame advance

### ISSUE THREAD

**Issue by Lavesiime** [Rubberduckycooly/Sonic-CD-11-Decompilation#165]
Whenever frame advance is active, the dimming proceeds even when the game is paused. This results in the screen dimming repeatedly without the game actually drawing, ending with a game that's entirely black.

![unknown](https://user-images.githubusercontent.com/70488825/168195013-727e4923-6d14-48ec-8672-3ea8a62e3a8b.png)
 
In case you couldn't tell, this is Palmtree Panic Act 1.

Also, adding onto my previous issue, this happens with 3d layers active as well.

![unknown](https://user-images.githubusercontent.com/70488825/168195464-158aec76-dc7a-47e8-a996-fe0d0b3631f3.png)

**Comment by Rubberduckycooly** [comment]
should be fixed as of https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/commit/02469db92b40edf6d21ce146a2c2c0d081aa4e4a
