### ISSUE TITLE
Building Flatpak error "cannot stat ./videos no such file or directory"

### ISSUE THREAD

**Issue by SlowPoke1000** [Rubberduckycooly/Sonic-CD-11-Decompilation#166]
The Data.rsdk file along with the video folder is present in the same directory where I'm building the Flatpak; it ends with 

"cp: cannot stat './videos': No such file or directory
Error: module soniccd: Child process exited with code 1"

**Comment by lsdxm** [comment]
Same issue here

**Comment by TheDrifter363** [comment]
Wanted to report, I'm having the same issues. No idea how to fix. The cp -r command runs fine outside of flatpak-builder.

**Comment by MegAmi24** [comment]
should be fixed with the pull request above
