### ISSUE TITLE
Graphics incorrectly displayed when returning to Main Menu (Mobile RSDK & HW Renderer)

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/Sonic-CD-11-Decompilation#168]
How to reproduce:

1. Use a Mobile version RSDK (use bytecode, not scripts), enable Hardware renderer.

2. Play the game, load into a stage. Exit stage from Pause Menu to go back to the Main Menu.

3. Every sprite should now be incorrectly displayed (with blurriness and a weird box around a majority of the sprites)

![image](https://user-images.githubusercontent.com/24783625/170837956-c03bc4a0-cb56-4f71-a6f1-b98c000c9c4b.png)

**Comment by Rubberduckycooly** [comment]
fixed as of f15a962
