### ISSUE TITLE
Can't build for psvita: Missing `GL/glew.h`

### ISSUE THREAD

**Issue by beelzebielsk** [Rubberduckycooly/Sonic-CD-11-Decompilation#169]
I got several errors while trying to build for the vita, but this is the one I can't get around.

```
/work/RSDKv3/RetroEngine.hpp:161:10: fatal error: GL/glew.h: No such file or directory
  161 | #include <GL/glew.h>
      |          ^~~~~~~~~~~
```

**Comment by parkerlreed** [comment]
Is this going through the docker method for Vita as mentioned in to Readme?

**Comment by beelzebielsk** [comment]
Yep

**Comment by parkerlreed** [comment]
> Yep. I did a little digging, and I'm not sure the Vita has glew as an available library. At least not through vdpm.

Yeah that was my thought too. GLEW is more desktop GL focused. I might give that a try later if nothing comes up.

**Comment by MystiK791** [comment]
I have the same issue. Has anyone found a fix yet?

**Comment by MegAmi24** [comment]
The Vita port (at least the one in this repo) is deprecated and is no longer expected to work. Closing.
