### ISSUE TITLE
Integer Scaling no longer an option

### ISSUE THREAD

**Issue by OldFinbar** [Rubberduckycooly/Sonic-CD-11-Decompilation#171]
I noticed that the integer scaling option isn't in the v1.3.0 settings.ini like it was in v1.1.2 and was wondering if there was still a way to enable it?

**Comment by Rubberduckycooly** [comment]
There is currently no way to enable integer scaling due to the new rendering backend in 1.3, the current available options are: 
0 = nearest neighbour
1 = linear filtering
