### ISSUE TITLE
Unplayable Decompilation?

### ISSUE THREAD

**Issue by Sonicthe06** [Rubberduckycooly/Sonic-CD-11-Decompilation#174]
How Can I Play This Decompilation On Steam If Its Removed?

![Screenshot 2022-07-08 194106](https://user-images.githubusercontent.com/105401700/178088632-9cdf7851-0860-4b42-a278-6cb3f3507c10.png)

**Comment by MegAmi24** [comment]
[The mobile version is still available.](https://gamebanana.com/tuts/14942)

**Comment by peterclaudius** [comment]
Sonic CD (Windows) Via Steam, from [Sonic Origins] don´t work
