### ISSUE TITLE
Dev menu defaults to JP soundtrack despite having the US one selected

### ISSUE THREAD

**Issue by shyguy85** [Rubberduckycooly/Sonic-CD-11-Decompilation#175]
I can enable and use the US soundtrack fine, but when i try using dev menu to warp into a different stage, the game always defaults to the JP soundtrack. If i go back into the normal menu, though, the us soundtrack is put back on.

**Comment by MegAmi24** [comment]
Script bug, can't be fixed, won't be fixed
