### ISSUE TITLE
Stereo 16-bit wav files cause crashes in the Dev Menu

### ISSUE THREAD

**Issue by PimpUigi** [Rubberduckycooly/Sonic-CD-11-Decompilation#179]
16-bit Stereo SFX files play fine in game, but the moment you try to either exit the Mods menu, or Exit the game itself through the Dev Menu, it causes a crash.
This is with a minimum of 1 SFX file replaced with a 16-bit Stereo SFX file. The files themselves play perfectly in game.

Neither 16-bit Mono nor 8-bit Stereo cause a crash.

**Comment by MegAmi24** [comment]
RSDK only supports 16-bit mono
