### ISSUE TITLE
where is the settings.ini file?

### ISSUE THREAD

**Issue by Apep-the-snek** [Rubberduckycooly/Sonic-CD-11-Decompilation#182]
i'm on arch linux, i can't find any settings.ini file anywhere, checked all the subdirectories. any help?

**Comment by parkerlreed** [comment]
```
(deck@steamdeck soniccd-git)$ soniccd-launcher 
Created data folder in '/home/deck/.local/share/soniccd', please copy the game's data files there and run this launcher again.
```

```
~/.local/share/soniccd
```

**Comment by parkerlreed** [comment]
I think you have to create settings.ini. I don't see it by default either.

**Comment by parkerlreed** [comment]
Found it

```
~/.local/share/RSDKv3/settings.ini
```

**Comment by Apep-the-snek** [comment]
bruh, i used the directory where i did the compilation (where i git cloned), i'm a total doofus when it comes to compiling things, lol. thank you though!
