### ISSUE TITLE
Game does not load settings.ini 

### ISSUE THREAD

**Issue by BombchuLink** [Rubberduckycooly/Sonic-CD-11-Decompilation#186]
OS: Arch linux 
Compiler: gcc 12.2.0 (using provided makefile)
Build version: Latest repo commit (13 hours ago)

The game doesn't load settings.ini upon boot. I have tested case sensitivity, and putting the game into a short length directory, but that didn't change anything. It is also loading Data.rsdk just fine, so it's not like it can't find the source folder.

**Comment by marioluigi751** [comment]
You need to check ~/.local/share/RSDKv3/ for any configuration files, if I recall, settings & mods are loaded from there.

**Comment by BombchuLink** [comment]
Ok, yeah it does load from there instead of from the folder the game is in now... There should probably be a launch flag that makes it check the directory the program it is in (if there isn't already)
