### ISSUE TITLE
which files from the apk are needed

### ISSUE THREAD

**Issue by IgnisPlasma** [Rubberduckycooly/Sonic-CD-11-Decompilation#188]
im trying to run this on windows 10. i download the x86 version but am unsure which assests are needed from my phones game files

**Comment by MegAmi24** [comment]
[The files aren't in the apk file](https://gamebanana.com/tuts/14942)

**Comment by IgnisPlasma** [comment]
where are they then?

**Comment by IgnisPlasma** [comment]
thank you i will try that now

**Comment by IgnisPlasma** [comment]
btw does it work with the free versions rsdk because it is still not working

**Comment by IgnisPlasma** [comment]
thx i finally got it working
