### ISSUE TITLE
Building the APK

### ISSUE THREAD

**Issue by Henrykado** [Rubberduckycooly/Sonic-CD-11-Decompilation#189]
when i try to build the apk on android studio i keep getting this error:

```
> Task :app:buildNdkBuildRelease[arm64-v8a] FAILED

C/C++: fcntl(): Bad file descriptor

C/C++: In file included from C:/Users/Henrique/Downloads/Sonic-CD-11-Decompilation-master/android/app/jni/src/dependencies/all/theoraplay/theoraplay.c:36:

C/C++: In file included from C:/Users/Henrique/Downloads/Sonic-CD-11-Decompilation-master/android/app/jni/src/dependencies/android/libtheora/include\theora/theoradec.h:24:

C/C++: In file included from C:/Users/Henrique/Downloads/Sonic-CD-11-Decompilation-master/android/app/jni/src/dependencies/android/libogg/include\ogg/ogg.h:24:

C/C++: C:/Users/Henrique/Downloads/Sonic-CD-11-Decompilation-master/android/app/jni/src/dependencies/android/libogg/include\ogg/os_types.h:154:12: fatal error: 'ogg/config_types.h' file not found

C/C++: #  include <ogg/config_types.h>
C/C++:            ^~~~~~~~~~~~~~~~~~~~

C/C++: 1 error generated.
C/C++: make: *** [C:/Users/Henrique/AppData/Local/Android/Sdk/ndk/22.1.7171670/build//../build/core/build-binary.mk:476: C:\Users\Henrique\Downloads\Sonic-CD-11-Decompilation-master\android\app\build\intermediates\cxx\Release\1q2n2f1d/obj/local/arm64-v8a/objs/main/dependencies/all/theoraplay/theoraplay.o] Error 1
```

**Comment by trandangmanghi2** [comment]
RSDKv3 Sonic CD

**Comment by MANGOM1LK** [comment]
I was having this specific issue and was able to fix it by going into ./dependencies/android/libogg/include/ogg/ and renaming "config_types.h.in" to "config_types.h". (By the way there's a typo in the dependencies .txt, it tells you to put the libvorbis source code in the libtheora folder)

That didn't get the project to build on my end, though. I suspect it has something to do with the Gradle version used in the project being incredibly outdated, Android Studio prompted me two seperate times to upgrade the Gradle version and told me the first time that the current Gradle version was unsupported.

**Comment by Leonx254** [comment]
There is a file inside `Dependencies/Android/` called `config_types.h`, copy and paste it into `libogg/include/ogg` then build again
