### ISSUE TITLE
A graphical bug on the title screen. 

### ISSUE THREAD

**Issue by MetalMaxMX** [Rubberduckycooly/Sonic-CD-11-Decompilation#19]
Host: Linux, albeit presumably all platforms given the Vita version also shows problems. 

A small graphical issue occurs on the title screen. Whenever you show up, on the rightside lower position of Sonic's left arm (or just slightly to the right of the "D" letter in the "SONIC CD" logo), there's a small vertical rectangle that looks glitched/broken. 
![tl-VHr-Faj-Pq0402919030220219605447589](https://user-images.githubusercontent.com/62585114/104403844-cb71f880-552f-11eb-8161-c41456371e19.png)

Not a dealbreaker, but does looks off. And when you start the game, said rectangle turns into black too.

**Comment by Rubberduckycooly** [comment]
thats a known bug, its due to the PC version of the game running in 400x240, rather than 424x240 like mobile vers, if you can somehow change the screenWidth to 400 instead of 424 its fixed, other than that its very minor and shouldn't break much
