### ISSUE TITLE
Android, Software Renderer: Leftmost pixels are instead rendered on the right edge of the screen.

### ISSUE THREAD

**Issue by Shockwave508** [Rubberduckycooly/Sonic-CD-11-Decompilation#194]
There appear to be some pixel alignment issues with RSDKv3 on my ultrawide phone, as some of the leftmost pixels are instead rendered on the rightmost edge of the screen. Game is still very much playable, but this is quite an eyesore.

Device: Xiaomi Black Shark 2 Pro (128GB)
Android OS: 10
CPU: Qualcomm Snapdragon 855+ (8 cores, 2.96GHz)
RAM: 8GB
RSDKv3 Build: Android, v1.3.0
Sonic CD Version: Android (Forever Release)
Screen Resolution: 2340x1080
![Screenshot_2022-10-02-00-44-14-384_com decomp rsdkv3](https://user-images.githubusercontent.com/32436386/193440350-d092a8a8-4c07-4a3a-9e6a-b46c299de08a.jpg)

**Comment by Leonx254** [comment]
fixed on https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/commit/d1188fd9fa72d5ab0e162cd860e766af1fd4d0a7
