### ISSUE TITLE
[Android] Graphical error on title screen

### ISSUE THREAD

**Issue by awe444** [Rubberduckycooly/Sonic-CD-11-Decompilation#198]
Using latest "actions" build (haven't tested any earlier builds) with Steam data.rsdk on Android 13, there's a graphical error to the right of Sonic on the title screen. Toggling HardwareRenderer from true to false changes the color of the error from black to grey, as seen in the following screenshots:
![Screenshot_20221109-210831](https://user-images.githubusercontent.com/97898022/200983923-26b06d59-a4de-4cc1-8324-cb373d004626.png)
![Screenshot_20221109-210950](https://user-images.githubusercontent.com/97898022/200983947-f2f375b2-a4a5-44e5-bd06-1bce4c19cb73.png)

The phone's aspect is wider than 16:9 so I wonder if that's the cause. Incidentally I cannot change the width via settings.ini (it seems to ignore my specified ScreenWidth value and always just fills the whole screen, despite changing Fullscreen to false, not sure if that's a separate issue or expected behaviour).

In game I am also experiencing the edge pixel problem (only when using software renderer) reported previously as https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/issues/194

**Comment by MegAmi24** [comment]
That's just how it looks due to how the title screen is coded, you can fix via mods

**Comment by TheBrockReal** [comment]
There's no mods to fix it

**Comment by TheBrockReal** [comment]
> That's just how it looks with screen widths higher than 400 due to how the title screen is coded in the Steam version, you can fix via mods

There's no mods 
Stop lying
