### ISSUE TITLE
Crash on special stage 5

### ISSUE THREAD

**Issue by FactorRott37** [Rubberduckycooly/Sonic-CD-11-Decompilation#199]
Every time I open the special stage 5 from the dev menu and try to move to the left, the game starts to bug the scenario and closes by itself

![Screenshot_20221111-165301](https://user-images.githubusercontent.com/90012425/201422998-4b7eadf2-fa95-4a34-90ee-60be5483fcfe.png)

**Comment by Leonx254** [comment]
this happens when you use a mobile data file without turning HardwareRenderer to 'true'
an alternative fix can be done by setting TxtScripts to true, regardless of used render
