### ISSUE TITLE
Game exit pressing dpad-right on Xbox 360 wireless controller

### ISSUE THREAD

**Issue by psicotron3** [Rubberduckycooly/Sonic-CD-11-Decompilation#20]
With the precompiled windows binary (x86 or x64) the games closes itself without any error message when pressing DPad-Right.

The game can be played without issues using the thumbstick, the issue only affect dpad-right. Changing the button function on settings.ini doesn't make any difference.

I'm running Windows 10 - 64 bits 18363.1256

**Comment by Rubberduckycooly** [comment]
this is an issue that's already been fixed, I just haven't had the chance to release an updated build of the game with all the fixes yet, the issue was due to misplaced code in the game event loop
