### ISSUE TITLE
scripts mods error in rsdkv3 mobile

### ISSUE THREAD

**Issue by Davidmarcos502** [Rubberduckycooly/Sonic-CD-11-Decompilation#202]
Guys, I can't run scripted mods on rsdkv3 mobile (this mod and Sonic cd and knuckles) I don't know what I do anymore, it's not just this mod, there are others too, how do I solve this?
![Screenshot_20221201-161046](https://user-images.githubusercontent.com/118953388/205140236-191e8a73-c996-45be-bc05-43fba1e38065.jpg)

**Comment by Leonx254** [comment]
Either you didn't setup the mods properly or you're using the wrong versions of the mods required
