### ISSUE TITLE
Tails' tails clipping through foreground objects

### ISSUE THREAD

**Issue by RabbitDeerYou** [Rubberduckycooly/Sonic-CD-11-Decompilation#220]
### Expected Behavior

Tails' entire sprite should be hidden behind sprites that are in the foreground.

### Actual Behavior

Most of the sprite is hidden, but his tails continue to show through when he's standing still or jumping (not if he's running).

### Steps to Reproduce

Go to literally any area that has a sprite in the foreground, which Tails will pass behind. The pseudo-3D area at the beginning of Palmtree Panic 1 is an obvious one.

### Screenshots

![tails3](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/88208234/82f5ef4c-667e-4047-9b24-23b9ecff3f6c)
![tails1](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/88208234/dfa022dd-1833-4d97-b169-1d5dfdf5d99f)
![tails2](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/88208234/18880df3-93f3-4768-9f01-f581d5135c4a)

### Decompilation Version

v1.3.1

### Game Version

Blit Release (Steam/XBOX 360/PS3)

### Script Platform Type

Standard

### Renderer Type

Software Renderer

### Platform

Windows 11

### Additional Comments

Every YouTube video of "Tails in Sonic CD" gameplay doesn't have this happen, and I can't find anyone else who's reported the same problem. I'm not using any mods or unusual settings. I've tried it on both the hardware and software renderers and both are the same. Possibly related: comparing my game with YouTube videos, it seems that in his standing and jumping poses, Tails' tails animate much more quickly than in other versions of the game, seeming to whip around as if the animation is playing at double speed.

UPDATE: Setting TxtScripts=false in settings.ini fixes the problem (the speed of his tails and the clipping through other sprites issue is gone), but it also means I'm unable to use any mods. Would still like a fix for this if possible!

**Comment by MegAmi24** [comment]
This happens because Origins added an extra draw layer that the Blit releases didn't have. We've already added some checks to make sure this layer isn't active when on the latter version.

> Setting TxtScripts=false in settings.ini fixes the problem

This means you're on an older version of the decompiled scripts. Newer versions include a workaround for this issue, so updating the scripts should fix the problem.

**Comment by RabbitDeerYou** [comment]
Thanks, seems I had the old scripts mistakenly downloaded, as you said!
