### ISSUE TITLE
Android application manifest version number does not match release

### ISSUE THREAD

**Issue by parkerlreed** [Rubberduckycooly/Sonic-CD-11-Decompilation#224]
### Expected Behavior

Version number to match

### Actual Behavior

Version number does not match

### Steps to Reproduce

1. Look at version in Android manifest

### Decompilation Version

1.3.1

### Game Version

Mobile (Pre-Sega Forever)

### Script Platform Type

Standard

### Renderer Type

Software Renderer

### Platform

Android

### Additional Comments

The manifest has the version set as 1.0 despite the release being 1.3.1. 

This throws off some update checkers that rely on seeing the correct version number.

**Comment by MegAmi24** [comment]
Fixed in af474eb and forgot tell you oops
