### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by KeeveeKoomoo** [Rubberduckycooly/Sonic-CD-11-Decompilation#228]
### Expected Behavior

When  I enter the command "cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=[vcpkg folder path here]/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_PREFIX_PATH=[vcpkg folder path here]/installed/x64-windows-static" sonic cd will be built into the build folder

### Actual Behavior

the cmd window returns an error "CMake error at cmakelists.txt:62 (include): include could not find requested file: platforms/msys.cmake

### Steps to Reproduce

I followed the instructions step by step given on the github
I got to the part where you input the above command, making sure to add the correct file paths in place of [vcpkg source here]  etc etc
Following output in screenshots

### Screenshots

![image](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/87249339/e2f786fb-cc99-4f5a-868d-23d530e8c55f)

### Decompilation Version

I'm not sure, whatever the latest is at the time of this bug report. Sorry :(

### Game Version

Sonic Origins

### Script Platform Type

Standard

### Renderer Type

Hardware Renderer

### Platform

Windows

**Comment by KeeveeKoomoo** [comment]
Also, something I tried to do to fix it was renaming the file named "windows.cmake" in the platforms folder to "msys.cmake".
This yielded a different error, none of the libraries I installed with vcpkg could be found, no matter where I placed the folders found in the "installed/x64.../include"

**Comment by KeeveeKoomoo** [comment]
Thanks lol if I was able to do that myself but didn't, I'm sorry it's like 2 in the morning

**Comment by KeeveeKoomoo** [comment]
I figured out why it was looking for msys.cmake, for some reason msys was being deducted as the platform as shown by this screenshot in visual studio
![image](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/87249339/902460db-2a02-4d48-8f50-69be525e8bbd)

**Comment by KeeveeKoomoo** [comment]
How soon should I expect to hear anything back about this?

**Comment by BooBerry** [comment]
Yeah, I haven't been able to compile this using cmake on Windows either, but I can on Linux.

Compiling via Visual Studio 2022 (once setting up the dependencies manually) works fine too.

**Comment by KeeveeKoomoo** [comment]
Would you be able to either walk me through setting up visual studio to build the decomp or show me where I can find some instructions on how to do so? I'm very new to building decompilations like this.

**Comment by KeeveeKoomoo** [comment]
> Yeah, I haven't been able to compile this using cmake on Windows either, but I can on Linux.
> 
> Compiling via Visual Studio 2022 (once setting up the dependencies manually) works fine too.

Linux gives the same errors
![image](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/87249339/9c7e8c64-df2f-470c-9dee-fdf175ecedce)

**Comment by BooBerry** [comment]
There's a video somebody made that should help.

https://www.youtube.com/watch?v=CO7GpbWuzDI

**Comment by KeeveeKoomoo** [comment]
> There's a video somebody made that should help.
> 
> https://www.youtube.com/watch?v=CO7GpbWuzDI

I've left a comment in that video already, I went there first

**Comment by KeeveeKoomoo** [comment]
I followed the video step by step and it still doesn't work, I even have the C++ desktop development thing installed in visual studio, something the author of the video forgot to mention in the video

**Comment by KeeveeKoomoo** [comment]
![image](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/87249339/08986e17-cf9d-4b0d-97ef-b653980c12b9)

**Comment by KeeveeKoomoo** [comment]
I don't know what I'm doing wrong, unless there is something that hasn't been included because it's common knowledge among people who compile stuff frequently.

**Comment by BooBerry** [comment]
Just tried compiling with both cmake and VS in Windows 11, and both work fine as long as the dependencies are met (and you modify the cmake command to add the full path to vcpkg and the triplet used, otherwise if you copy and paste as-is it won't work.

**Comment by KeeveeKoomoo** [comment]
one sec, I'm gonna screen record a video of me trying to compile it whist following the instructions, if you don't end up seeing the video, it's because it decided to work when I was trying to show somebody else lol.

**Comment by KeeveeKoomoo** [comment]
Right so one thing I did notice was in the dependencies.txt, there are some instructions that were not mentioned in the video, I will try those before I show my screen record, as I don't really think my screen record will help too much as I am just following the instructions and it's very similar to the video that you sent to me

**Comment by BooBerry** [comment]
If you're going the vcpkg+cmake route, you don't need to follow the dependencies.txt instructions. But following them should allow it to compile in Visual Studio.

**Comment by KeeveeKoomoo** [comment]
![image](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/87249339/b87a0345-cb02-4848-b42d-e44d1bf5f8b2)
Any ideas what to do here? I made sure it's the release version

**Comment by MegAmi24** [comment]
Closing this since there doesn't seem to be any interest in solving the original problem
