### ISSUE TITLE
Shields and Time Warp

### ISSUE THREAD

**Issue by NoUserHere1** [Rubberduckycooly/Sonic-CD-11-Decompilation#236]
### Expected Behavior

Elemental Shields working and Time Overhaul

### Actual Behavior

Elemental Shields break with only one sprite and you only get regular Shield. And Time Overhaul isn't working, only the warping stage, after that, you time warp like vanilla sonic cd but with flames and don't get the invicibility/speed shoes you had before

### Steps to Reproduce

1. I made a fresh RSDKv3 folder
2. Put everything correctly, with updated Scripts and the Data folder which has everything updated
3. Installed Sonic CD: Miracle Edition and MegAmisAdditions (only these two)
4. Loaded the game with software render and .txt Scripts forced
5. Got a Elemental Shields monitor and got a 1 frame fire shield flame
6. Restarted the stage and didn't go get the shield
7. Time Traveled but it glitched

### Decompilation Version

v1.3.2

### Game Version

Mobile (Sega Forever)

### Game Revision

v3.4.10

### Script Platform Type

Mobile

### Renderer Type

Software Renderer

### Platform

Android

### Additional Comments

Followed all the steps to intalling it correctly, but no shot, can anyone know what's the reason for these two problems?

**Comment by MegAmi24** [comment]
We do not provide support for mods. Please contact the mod creators instead.

**Comment by NoUserHere1** [comment]
Thank you, i will be providing issues from the base game itself.
