### ISSUE TITLE
Data.rsdk from the Android version

### ISSUE THREAD

**Issue by kenderipa** [Rubberduckycooly/Sonic-CD-11-Decompilation#239]
### Expected Behavior

.obb cache is expected

### Actual Behavior

No .obb cache at all

### Steps to Reproduce

Hello, I have a question. The Android version of Sonic CD that I own doesn't install the .obb cache that I could rename and use as data.rsdk. Instead, the multi-apk principle is used. In one of the apk's I can find all the data needed: data.rsdk.xmf and cutscenes. However, the apk containing this data is not recognized by the engine if renamed to data.rsdk. If I extract all the data from it and rename Data.rsdk.xmf to data.rsdk, the game works, but cutscenes are not shown. I tried to pack all the data to a file named data.rsdk, but the engine still crashes. Any suggestions here? Thanks!

### Decompilation Version

1.3.2

### Game Version

Mobile (Sega Forever)

### Script Platform Type

Mobile

### Renderer Type

Hardware Renderer

### Platform

Android

**Comment by MegAmi24** [comment]
The method you used that got the game working is the intended method, as the decomp is not compatible with the cutscene files from the mobile version; only the Steam version's cutscenes work.
