### ISSUE TITLE
[Linux] Non-x360 controllers (like my DS4) don't work when Steam Input is active

### ISSUE THREAD

**Issue by NerosTie** [Rubberduckycooly/Sonic-CD-11-Decompilation#24]
I have a DualShock 4, if I connect my controller when Steam is open, meaning Steam Input is active, the controller doesn't work with Sonic CD Decomp. If I quit Steam, or switch off Steam Input, and reconnect my controller, it works.

No issue with my Xbox 360 controller, with or without Steam.

I think there is an issue with SDL somewhere... (I can play with my DS4 with other open-source engines when Steam Input is active without issue, Sonic CD Decomp is the exception)

I'm on Linux (Arch).

**Comment by parkerlreed** [comment]
@SergeyLatyshev Z and X
