### ISSUE TITLE
vcpkg.exe install glew sdl2 libogg libtheora libvorbis --triplet=x64-windows-static cannot download powershell

### ISSUE THREAD

**Issue by RandomScoutdigoFan** [Rubberduckycooly/Sonic-CD-11-Decompilation#242]
### Expected Behavior

Running this command should first download Powershell

### Actual Behavior

It fails to download then retries 3 times before giving up. I tried switching to drives with more space yet it still was unable to download

### Steps to Reproduce

I assume its because of me not installing all the optional Visual Studio optional dependencies or due to low storage space but i have the batch file and my c drive has enough space if not more.

### Screenshots

![image](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/assets/173638689/6a2a3a69-b6b8-4280-9efc-292daf290f2d)

### Decompilation Version

Commit date: Jun 24, 2024 Manual Source Code

### Game Version

Sonic Origins

### Script Platform Type

Standard

### Renderer Type

Software Renderer

### Platform

Windows

### Additional Comments

I do want to know if its just a storage issue or not as I have 167 MB (yes MB) before it quit.

**Comment by MegAmi24** [comment]
This issue seems to be solely related to vcpkg and not the decomp itself, so I don't think we can help much here.
