### ISSUE TITLE
Special Stage 5 breaks the game

### ISSUE THREAD

**Issue by Pyra2004** [Rubberduckycooly/Sonic-CD-11-Decompilation#27]
**Moving the camera will show visual errors, and will crash the game.**
VSync does not fix this issue. I uh... dont think i can complete special stage 5... ):
also if u can id like options that are in the ini to be editable in the game idk how doable that is though
**NOTICE: The game only loads a visual error if you press "left", which means it's possible to complete the special stage as long as you do not press the "left" key.**

https://user-images.githubusercontent.com/69493780/104962564-4f980600-599e-11eb-8fca-c95b8961c23c.mp4

**Comment by TerraKingLazure** [comment]
Having the same issue today. How was this not fixed a year ago?

**Comment by Lavesiime** [comment]
It seems that this is an issue that arises from using a Hardware Rendered RSDK Data file with the decompilation running in Software Rendering mode. If you turn `HardwareRenderer` to true in the settings.ini, does the issue still persist?

**Comment by InfamousLazure** [comment]
Special stage works correctly now, but as a side effect, the main menu UI and other menus are invisible and show no text.

**Comment by MegAmi24** [comment]
Are you using a Data.rsdk file from the mobile version or the Steam version?

**Comment by InfamousLazure** [comment]
Mobile, because it was updated more than the Steam version.

**Comment by MegAmi24** [comment]
The main menu UI shows up fine on a mobile Data.rsdk with Hardware Rendering for me. Try ripping the Data.rsdk file from the mobile version of CD again and see if that fixes the problem.
![image](https://user-images.githubusercontent.com/7158344/171052940-358640e4-ae32-4638-b287-a5f386608769.png)

**Comment by InfamousLazure** [comment]
No dice. Still doesn't show any buttons or text.
![_-_](https://user-images.githubusercontent.com/77689987/171313053-16441dfa-7318-4a34-b813-4b25818a5c95.png)

**Comment by Leonx254** [comment]
fixed in https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/commit/812785e9ddad28151400ab31d57282d7b64b9622
