### ISSUE TITLE
Videos play without audio

### ISSUE THREAD

**Issue by jedinjapan** [Rubberduckycooly/Sonic-CD-11-Decompilation#28]
On the Windows x64 and x86 builds using the Steam release resources, the video files are correctly detected and playback upon starting a new save, but there is no audio for the intro and presumably other videos later in the game.

Exact filename is Opening.ogv

Attempted to work around this with notes on other repos using OpeningUS.ogg file with [videoname][US].ogg present as well, but was unsuccessful. Unsure if that workaround is still enabled in repo, or if something about the exact naming applies here.

**Comment by jedinjapan** [comment]
Already resolved, not in 1.0.0 build yet.

**Comment by ViperAcidZX** [comment]
Sorry to necro this issue, but I am having this issue still with 1.0.0 on the x86 build.

**Comment by dilworks** [comment]
Happened to me after clearing a game with Sonic and all Good Futures - I got no music on the ending credits video!

Linux x86_64 here.
