### ISSUE TITLE
[Request] Is it possible to hide the control overlay?

### ISSUE THREAD

**Issue by seagull** [Rubberduckycooly/Sonic-CD-11-Decompilation#30]
Hi;
I appreciate your ability to alter the game's behaviour may be limited, but is it possible to hide the touchscreen control overlay like you did with the Sonic 1 and 2 decompilations?
Cheers

**Comment by parkerlreed** [comment]
FWIW if you use the PC version there's no overlay.

**Comment by seagull** [comment]
Good tip, thanks.
