### ISSUE TITLE
Game crashes when pressing "Right" on D-Pad

### ISSUE THREAD

**Issue by PolarStar64** [Rubberduckycooly/Sonic-CD-11-Decompilation#31]
When playing, at any point if I press right on the d-pad, the game crashes. Stick still works fine.

OS: Windows 10-1909
Device: GPD Win 2
Controller: Xbox 360
Release: 1.0.0
RSDK: Steam
settings.ini: https://pastebin.com/2eENgjCS

**Comment by Rubberduckycooly** [comment]
this is a known bug, and it has been fixed, the fix will be in the next build (which should release later this week)
