### ISSUE TITLE
Save Select screen glitched on latest mobile version

### ISSUE THREAD

**Issue by hkight** [Rubberduckycooly/Sonic-CD-11-Decompilation#33]
When using the Data.rsdk from iOS version 3.0.6 (MD5: 6649dd9866d07d6e588e29b101da3488), some of the menu graphics look glitched, most notably the save select screen.

![Sonic CD 1_19_2021 6_11_22 PM](https://user-images.githubusercontent.com/18399988/105105329-e8ec1880-5a81-11eb-9e31-cf55b7c68381.png)

The Christian Whitehead logo also does not blend properly when transitioning.

![Sonic CD 1_19_2021 6_15_53 PM](https://user-images.githubusercontent.com/18399988/105105646-7a5b8a80-5a82-11eb-8b91-67c69105c061.png)

This does not seem to happen with the Data.rsdk from the Steam version (MD5: 78a03b962acf3e2622addab9cdb8e2ce).

**Comment by Rubberduckycooly** [comment]
the save screen is built like that because of the way that they put ads there, so without script mods this cannot be fixed, the CW logo issue is due to the decomp currently not supporting "HiRes mode" which is used to render some things in higher quality, support for it is planned in the future
