### ISSUE TITLE
Title Screen doesn't reflect Soundtrack choice.

### ISSUE THREAD

**Issue by DarkLink1996** [Rubberduckycooly/Sonic-CD-11-Decompilation#34]
This is a bug carried over from the PC Port. The game doesn't load the soundtrack setting on boot, instead defaulting to the Japanese soundtrack and loading the setting upon entering the menu. As a result, even if the US soundtack is selected, the title screen and demos all play the Japanese soundtrack until quitting back to the title screen from gameplay, where now they will play the selected soundtrack.

**Comment by Rubberduckycooly** [comment]
this is a bug with the PC scripts, so its not a decomp issue, you can use the mobile data.rsdk files to fix this, or wait a bit for us to add a mod loader and then use my CD refined mod that contains the fix
