### ISSUE TITLE
[Request] More in-depth soundtrack customization. 

### ISSUE THREAD

**Issue by DarkLink1996** [Rubberduckycooly/Sonic-CD-11-Decompilation#35]
I think it would be nice to have the ability to select the soundtrack per Zone, if it's possible to do so.

For instance: 

Title Screen: **[JP]** [US]
Opening: [JP] **[US]**
Palmtree Panic: **[JP]** [US]
Quartz Quadrant: [JP] **[US]**
Good Ending: **[JP]** [US]
Bad Ending: [JP] **[US]**

**Comment by Rubberduckycooly** [comment]
this would (and could) be done via a script mod, as the game logic is managed via external scripts, rather than built into the engine itself

**Comment by DarkLink1996** [comment]
Ah, I see. Thank you for the clarification. To avoid opening a second request issue, I'm going to assume that applies to playable characters as well, and as such a Knuckles character port and following Tails AI would be handled externally as well.
