### ISSUE TITLE
Help & Options Not Working

### ISSUE THREAD

**Issue by harper6202** [Rubberduckycooly/Sonic-CD-11-Decompilation#36]
Trying to use any of the options under Help and Options makes the screen fade to black for a second and then nothing else happens. The Settings options won't show up.

**Comment by Rubberduckycooly** [comment]
they're hardcoded into the original games, which isn't replicated in this decompilation and to be honest wont ever be, the settings.ini file is a replacement (and more) for settings so there shouldn't be any issues there

**Comment by DarkLink1996** [comment]
The spindash setting doesn't appear to be on the .ini, which leaves this version feature incomplete until a replacement is added.
Not that it's a major deal, with the default Sonic 2 style being leagues better than the CD style.
