### ISSUE TITLE
Windows x64 Build doesn't launch the game

### ISSUE THREAD

**Issue by ViperAcidZX** [Rubberduckycooly/Sonic-CD-11-Decompilation#37]
I was trying to use the Windows x64 build of the decompilation with my own Steam copy of Sonic CD but it does not want to launch at all for me and I don't know why, yet for some reason the x86 build is able to launch the game.

My system's specs:

- **OS:** Windows 10 Home, 64-bit
- **RAM:** 8GB DDR3
- **GPU:** Nvidia GeForce GTX 960
- **CPU:** AMD FX-4350

**Comment by Rubberduckycooly** [comment]
Can you send a screenshot of the folder with the x64 bit executable and datafile in it?

**Comment by ViperAcidZX** [comment]
Here's a screenshot of folder with the 64-bit executable with the data file from my own copy of the game on Steam.

![steam_2021-01-21_01-50-01](https://user-images.githubusercontent.com/19318128/105309609-ffca6200-5b8a-11eb-8c78-6cac51068aa3.png)

**Comment by Rubberduckycooly** [comment]
hm, I still dont really know why it wouldn't run the game, my only other idea is for you to set `EngineDebugMode` to `true` in the settings.ini file, so it generates a log.txt file and send that log file so I can have a better guess as to what may be going wrong

**Comment by ViperAcidZX** [comment]
I'm trying that but the x64 build doesn't even produce a log.txt file at all when I try to launch it. Here's a gif recorded with ShareX showing my attempts to launch it with ``EngineDebugMode`` enabled.

![%pn_2021-01-21_11-52-56](https://user-images.githubusercontent.com/19318128/105383741-6d07e280-5bdf-11eb-9d5e-b0e45257eeef.gif)

**Comment by Rubberduckycooly** [comment]
that is really weird, that means the game isn't even getting to the stage where it can open anything at all, I've got almost no clue what's causing that but I'll continue to look into potential fixes

**Comment by ViperAcidZX** [comment]
So I decided to try v1.1
.0 64-bit build and it managed to create a log this time after enabling debugging mode and this is the report I got from the log file with the 64-bit build.

[log.txt](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/files/6094738/log.txt)

**Comment by ViperAcidZX** [comment]
So I tried to see if I can compile the Sonic CD Mobile Decompilation myself and I ran into these errors even though I did installed all the packages and followed the instructions for the MSYS2 compilation. I'm not sure if this has any correlation as to why the 64-bit build refuses to work on my PC.

![mintty_2021-03-07_18-27-15](https://user-images.githubusercontent.com/19318128/110258897-d31fad80-7f72-11eb-8ad4-9e15665a5bfe.png)

**Comment by ViperAcidZX** [comment]
I wanted to update that, after reformatting my computer with DBAN and performing a clean re-install of Windows and the necessary drivers, the 64-bit version of the Sonic CD Decomp on the Releases page as well as compiling the executable via MSYS64 are finally working on my PC. It seems that something was corrupted and causing it (and other programs) to not work at all, but after re-installing the OS it fixed the issue.
