### ISSUE TITLE
B button suspends UWP application

### ISSUE THREAD

**Issue by elgarlic** [Rubberduckycooly/Sonic-CD-11-Decompilation#44]
As the title says. On Xbox Series X (built with the UWP sln as described), the B button suspends the application and displays the xbox dashboard. It resumes fine, and the B button also works as intended, functioning as a back button in the menus. But each time you want to go back in the menus, it requires resuming the app.

**Comment by Rubberduckycooly** [comment]
this should be fixed with PR #45, and if you rebuild the game should no longer suspend when pressing the B button
