### ISSUE TITLE
(Windows 10) Can't get into fullscreen

### ISSUE THREAD

**Issue by JohnnyTex** [Rubberduckycooly/Sonic-CD-11-Decompilation#46]
I played and beat the Sonic 2 decomp, playing through Sonic 1 rn. Those work well in fullscreen, but the Sonic CD decomp can't do it at all. Every time I try and save fullscreen as "true", when I open the game it just resets back to "false". I could set it to be borderless window mode at 5, but then the screen's cropped. Tried messing w/ the base width, that didn't go too well.

**Comment by Rubberduckycooly** [comment]
This is a known bug that's been fixed, the fix will be in the next build which is releasing in a few days
