### ISSUE TITLE
Hang after SEGA sound + logos

### ISSUE THREAD

**Issue by voltagex** [Rubberduckycooly/Sonic-CD-11-Decompilation#47]
![image](https://user-images.githubusercontent.com/159567/105509472-a3e61180-5d21-11eb-8025-c726d8b0e9d1.png)

data.rsdk is patch.49.com.sega.soniccd.classic.obb from the Android version of the game. There's no log I can see.

**Comment by MANGOM1LK** [comment]
reproduced this using the same RSDK, use the Steam or iOS version's RSDK for now

**Comment by Rubberduckycooly** [comment]
this is likely due to the age gate screen not being accounted for, as I was unaware it even existed since I used pre-sega forever rsdks for testing, this as been fixed and will be in the next build
