### ISSUE TITLE
Sega logo, C.W. logo and fonts on "How to play" appear garbled

### ISSUE THREAD

**Issue by vanfanel** [Rubberduckycooly/Sonic-CD-11-Decompilation#50]
Hi there,

I just built this AWESOME port/remake on my GNU/Linux systems (X86_64 for now, the Raspberry Pi will follow!) and I am really in awe with the implications of this. Because of that, I deeply thank you for your work!!

-My test builds are based on the latest SDL2 hg versions.
-My Data.rsdk file comes from the Android APK 2.0.0 version.

I have noticed that text is garbled on the Information/How-To-Play screen: fonts seems to pixelated and text is unreadable.
Same happens with the C.W. logo: the text is unreadable in a similar way.
Also, the scaling on the SEGA logo looks too pixelated too.

Any idea on whats wrong? I don't see any internal SDL errors...

Thanks!

**Comment by ToruTheRedFox** [comment]
that's because it's drawn into the 424x224 screen buffer, which the original game seems to increase the resolution of for those screens

**Comment by vanfanel** [comment]
@ToruTheRedFox Ah! That makes perfect sense :)
In SDL2, there's no need to change the resolution or the screen size to show different sized images, so I guess that's easy to fix?

**Comment by ToruTheRedFox** [comment]
the game already changes the resolution for the special stages, so I don't think it would be too hard to do that

just need to figure out how the original game checks for those screens

**Comment by Rubberduckycooly** [comment]
the mobile versions contained the option for a "Hi Res" mode, that seemed to change the rendering settings, though I am still unable to figure out what exactly it's doing as its all a bunch of openGL calls due to the mobile versions having a HW renderer vs a SW one like the PC has, if it's ever figured out how to properly replicate "Hi Res" mode, it'll be added, but its not super high priority due to it just being a few slight graphical bugs that don't affect the game experience

**Comment by vanfanel** [comment]
@Rubberduckycooly Thanks for taking the time to answer :)
I agree: it's a veeery minor thing anyway.

As for the HW/SW renderer: Do you mean the original engine renders the game tiles and sprites using OpenGL calls directly? 
SDL2 uses OpenGL to render under the hood, too (but not at low level, but for screen presentation).

**Comment by ToruTheRedFox** [comment]
hardware rendering as in it renders absolutely everything on the GPU, apart from maybe applying palettes on the CPU (because doing that on the GPU gets very messy, trust me, I've been there)

**Comment by ToruTheRedFox** [comment]
with software rendering here, the only thing that the GPU does is render the final framebuffer to the screen, but that's if SDL chooses to, otherwise, that's done in software too
