### ISSUE TITLE
(REQUEST) Rework script folder for mod compatibility

### ISSUE THREAD

**Issue by Piccadili-Hill** [Rubberduckycooly/Sonic-CD-11-Decompilation#53]
Hi,

The problem with the script folder by default is that it contained only .bin file

The PC version contained folders that have the exact same name as the .bin file from the android version. However those folders have .txt file into it.

**I have try to use the script folder from PC version into the data folder from android version, then i remove the ByteData file. The game is running but crash after the title screen. 
So to make it simple, I think you can use the same folder as the PC version but you have to edit something into it to avoid crashing the game.**

So the mod are on .txt file only.

Bonus: The script will let us have the haptic option for vibration

Thus it would be very kind if the android version script can be converted

**Comment by ToruTheRedFox** [comment]
you need to remove the ByteCode folder, and paste all of the text script folders into the now empty Scripts folder in Data

**Comment by Piccadili-Hill** [comment]
> you need to remove the ByteCode folder, and paste all of the text script folders into the now empty Scripts folder in Data

the game start directly by the sonic title screen and then crash "black screen" once I press start

**Comment by ToruTheRedFox** [comment]
you wouldn't be able to use a lot of PC script mods with that, so your best bet is to just use the Steam version's data instead, and change the ScreenWidth in the INI to 400

**Comment by Rubberduckycooly** [comment]
we're working on a *proper* mod loader that will handle mods in a much cleaner manner than what we have right now, it will be avaliable in the 1.2.0 build (next build will be 1.1.0)

**Comment by Piccadili-Hill** [comment]
> we're working on a _proper_ mod loader that will handle mods in a much cleaner manner than what we have right now, it will be avaliable in the 1.2.0 build (next build will be 1.1.0)

alright I will wait. And I also wanted to say the special stage 5 crash the game

**Comment by Piccadili-Hill** [comment]
> you wouldn't be able to use a lot of PC script mods with that, so your best bet is to just use the Steam version's data instead, and change the ScreenWidth in the INI to 400

ok

**Comment by Rubberduckycooly** [comment]
these issues have been solved and will be in the next builds
