### ISSUE TITLE
[Question] Where should the videos go with the PC data?

### ISSUE THREAD

**Issue by vanfanel** [Rubberduckycooly/Sonic-CD-11-Decompilation#54]
Hi,

On GNU/Linux (I guess any other POSIX system is the same), when using the Android data (Data.rsdk) I simply have to put the videos, in OGV format, inside a directory called "videos" in the same directory as the soniccd executable.

However, where do the videos go when using the Android Data.rsdk?
I have read in some closed issues that MP4 videos are not compatible with the engine. So, I guess OGV videos should work along with the Android data, shouldn't they? Sure I am missing something here :)

**Comment by ToruTheRedFox** [comment]
I'm fairly sure the mobile scripts call videos differently to the Steam scripts
oh and *Data.rsdk

**Comment by Rubberduckycooly** [comment]
all videos are loaded from `[CWD]/videos/`, mobile versions load `[videoName]`/`[videoName]US`, while the PC versions only load `[videoName]` but have 2 bitstreams (audio streams) to support JP/US osts

**Comment by vanfanel** [comment]
@ToruTheRedFox You are right, it's Data.rsdk, not Data.fsdk :+1: 

@Rubberduckycooly So, for the PC version, for example video/opening.ogv should be recognized by the scripts in Data.rsdk, right?
That's what I have and only the Android version recognizes it. The PC version does not.

**Comment by Rubberduckycooly** [comment]
@vanfanel "video**s**/opening.ogv" should be recognised by both versions, yeah, the PC version will use "opening.ogv" for US and JP, mobile will instead look for "videos/openingUS.ogv"

**Comment by vanfanel** [comment]
> @vanfanel "video**s**/opening.ogv" should be recognised by both versions, yeah, the PC version will use "opening.ogv" for US and JP, mobile will instead look for "videos/openingUS.ogv"

Ah! I got the PC videos to work.
But listen: there's a small problem here. The PC version needs "videos/Opening.ogv", while the ANDROID version looks for "videos/opening.ogv".
I am running this engine on GNU/Linux, which is case-sensitive so maybe that's the problem?

**Comment by Rubberduckycooly** [comment]
yeah, we'll work on more case-sensitive support asap, as it's been a problem for others as well

**Comment by vanfanel** [comment]
@Rubberduckycooly Thanks A LOT, really. This project is AWESOME, it makes me very, very, veeeery happy.
I have just built Sonic CD again with latest sources on GNU/Linux, no X11, and I have it running while I cook, just to enjoy the demo mode in the background. True, simple happiness. I don't know how to thank you for this, really! :)
