### ISSUE TITLE
Help & Options menu issues

### ISSUE THREAD

**Issue by Aryudsoh** [Rubberduckycooly/Sonic-CD-11-Decompilation#56]
How to play is illegible.

Controls and Settings are inaccessible.  Controls is not a big deal but settings lets you disable spin dash etc.

**Comment by Rubberduckycooly** [comment]
I'm adding an option for spindash options in the settings.ini, the rest of the settings are already in the ini file, and how to play is broken due to the PC version lacking support for "Hi Res" mode
