### ISSUE TITLE
(Vita) Use a different SDL2 port maybe?

### ISSUE THREAD

**Issue by ToruTheRedFox** [Rubberduckycooly/Sonic-CD-11-Decompilation#62]
The SDL2 port that's currently used doesn't seem to support the entirety of SDL2's featureset (most notably, no bilinear filtering, completely defeating the point of enhanced scaling), while https://github.com/isage/SDL-mirror promises to have support for all of SDL2's featureset.

**Comment by Clownacy** [comment]
Yes please. That would hopefully remove the need for [this horrible little hack](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/commit/ea73a8959173cb335afd6b595bc8c0f12b1da436#diff-743207e7e248f3db481775b6316d2ec4d68a9ab26971d6d418b99e96c3457ff7).

**Comment by Rubberduckycooly** [comment]
though this is still probably an issue, the base decomp no longer (and really shouldn't have ever) supports the vita version, I would advise making an issue on Xee's fork [here](https://github.com/Xeeynamo/Sonic-CD-11-Decompilation) to have that be fixed should the issue still persist
