### ISSUE TITLE
Pre-Sega Forever Android RSDKs prevent pausing

### ISSUE THREAD

**Issue by MANGOM1LK** [Rubberduckycooly/Sonic-CD-11-Decompilation#66]
Pausing is bound to B in Sega Forever versions of the game, and the Steam RSDK binds it to Start as expected, however pre-Sega Forever Android versions have no pause button bind at all. Pressing Start is the only way to get past the title screen, so it *can* detect the Start button. Is it possible these versions required users to tap the on-screen pause button? If so, mouse support might be cool, but otherwise there wouldn't be much you could do...

**Comment by Rubberduckycooly** [comment]
That's exactly correct, it checks for the on screen button press rather than start for whatever reason. As for mouse support, it's already added and should work to mimic the touch screen

**Comment by MANGOM1LK** [comment]
Mouse input doesn't seem to work in fullscreen mode, annoyingly. I didn't test it in windowed mode initially, otherwise I would have found this out sooner, probably.
