### ISSUE TITLE
Screen Height/Scaling 

### ISSUE THREAD

**Issue by Hilosiak** [Rubberduckycooly/Sonic-CD-11-Decompilation#67]
Like an option of screen width there could be a use for screen height or scaling, example: https://www.youtube.com/watch?v=zBw-0ohINL8&ab_channel=CodenameGamma

**Comment by Rubberduckycooly** [comment]
The engine is very hardcoded to use 240 as the base screen height, which is why to change it you have to recompile the game, we can look into making it an option but I wouldn't count on it happening anytime soon
