### ISSUE TITLE
[QoL Feature] Sonic CD Decomp missing Exit Game in Game Menu

### ISSUE THREAD

**Issue by MasterEmerald** [Rubberduckycooly/Sonic-CD-11-Decompilation#69]
Sonic 1 and 2 Decomps have this menu item, making it easy to terminate the program and exit the games when running in Full Screen mode.... meanwhile, the same is missing in the Sonic CD Decomp menu list.

Please consider adding it if possible.

**Comment by parkerlreed** [comment]
Scroll down... 
![image](https://user-images.githubusercontent.com/841440/105740427-3b588980-5f07-11eb-88bf-cc57ed0f10a0.png)

**Comment by MasterEmerald** [comment]
I was thinking more along the line of the DEV menu.... consider below - Sonic 1/2 2013 vs Sonic CD 2011
As crude as it is (pre upcoming v1.2+ changes) - its functional and quick to work with.
Any chance to see 'Exit Game' on the dev menu of Sonic CD 2011 decomp?

![DevMenu_ExitGame](https://user-images.githubusercontent.com/77983350/105755782-c93d7000-5f19-11eb-9ab1-52344f491fcd.PNG)

**Comment by Rubberduckycooly** [comment]
we'll add this feature in the next build, thanks for the suggestion!
