### ISSUE TITLE
[Good first issue] I cannot find the rsdk file

### ISSUE THREAD

**Issue by MechaMaster** [Rubberduckycooly/Sonic-CD-11-Decompilation#72]
Hi,
I have just today tried to extract my legally obtained .apk file and its assets in order to find the data.rsdk file to play the decompilation. Unfortunately, it's been unsuccessful and I have no idea why. I assume that this Sonic CD decompilation works the same way as the recent Sonic 1 and 2 Decompilation which I have no problem getting work, if my assumption is wrong can anyone direct me to a tutorial or at the very least provide a solution, whichever will be greatly appreciated. Thank You!

**Comment by vaguerant** [comment]
Hey there, Sonic CD is actually different. If I recall correctly, the `Data.rsdk` is found in the folder `Android/obb/com.sega.soniccd.classic` (working entirely from memory, apologies for any errors). The file you want is the one called `patch`, not the one called `main`. The exact filename will vary depending on the version you have downloaded. This file *is* your `Data.rsdk`, you will need to rename it and change the file extension to use it.

It's worth noting that the Steam version `Data.rsdk` is strongly recommended and has had the most testing--the Android version does have some issues with the decomp, the worst of which is an unavoidable crash on Special Stage 5.

**Comment by MechaMaster** [comment]
> Hey there, Sonic CD is actually different. If I recall correctly, the `Data.rsdk` is found in the folder `Android/obb/com.sega.soniccd.classic` (working entirely from memory, apologies for any errors). The file you want is the one called `patch`, not the one called `main`. The exact filename will vary depending on the version you have downloaded. This file _is_ your `Data.rsdk`, you will need to rename it and change the file extension to use it.
> 
> It's worth noting that the Steam version `Data.rsdk` is strongly recommended and has had the most testing--the Android version does have some issues with the decomp, the worst of which is an unavoidable crash on Special Stage 5.

Hi, thank you for your help, I've found the file called "patch.49.com.sega.soniccd.classic.obb" but I am clueless on what to rename the extension. In case you need to know my mobile version of Sonic CD, it's version 2.0.0.

**Comment by vaguerant** [comment]
You just need to rename that file to `Data.rsdk`, so `rsdk` is the extension. You don't need to open that file or anything to *get to* the `Data.rsdk`, that *is* the file, that's just the filename it has on Android.
