### ISSUE TITLE
Title screen background graphical error.

### ISSUE THREAD

**Issue by sylveon-irl** [Rubberduckycooly/Sonic-CD-11-Decompilation#73]
There's a "hole" behind and to the right of Sonic on the title screen. I don't recall this issue being there in the original release.

using 1.1.0 win64.

Screenshot:
![image](https://user-images.githubusercontent.com/33585928/105933560-451be300-6014-11eb-883f-ec96417b86a7.png)

**Comment by Rubberduckycooly** [comment]
this is a steam-related bug, to fix it you can either use a mobile data.rsdk file which properly sets the resolution to 424x240 like other rsdk games, or set `screenWidth` to 400 in the ini to align it with the PC version, which for some reason uses 400x240
