### ISSUE TITLE
Title screen music is the JP soundtrack even when US is selected.

### ISSUE THREAD

**Issue by sylveon-irl** [Rubberduckycooly/Sonic-CD-11-Decompilation#74]
I have the US soundtrack selected, but the title screen plays the JP music. The music for the title screen demos is the JP soundtrack as well.

When I go to the menu, the US menu music begins playing, and starting a file will use the US soundtrack.

If I then use the dev menu to go anywhere else in the game, it will return to using the JP soundtrack. However, if I return to the main menu from the dev menu, it will switch back to the US soundtrack.

Also, if you return to the title screen from in-game using the non-dev pause menu... that's the only way I have found to get the US music on the title screen and demos.

It's almost like the initialization of the game and the dev menu is setting it to JP always, and only the main menu screen loads the soundtrack choice and sets it correctly.

Using 1.1.0 win64.

**Comment by Rubberduckycooly** [comment]
this happens on steam-rsdk files only, the mobile RSDK files have been updated to fix this issue, its not a decomp bug, but rather one related to the game's scripts
