### ISSUE TITLE
Is there a way to extract Data.rsdk file from android?

### ISSUE THREAD

**Issue by lividhen** [Rubberduckycooly/Sonic-CD-11-Decompilation#76]
Unlike sonic one and two, there doesnt seem to be a data.rsdk.xmf in assets. Is it packed into the resources.arsc file? Is it compressed into a different format? Is it extracted with loose files somewhere? Is it in a different place (not in the apk) entirely?

Unrelated... What in the world is Pop Jam/spacepop...? And why is it in the assets folder?

**Comment by nor2101** [comment]
> 
> 
> Unlike sonic one and two, there doesnt seem to be a data.rsdk.xmf in assets. Is it packed into the resources.arsc file? Is it compressed into a different format? Is it extracted with loose files somewhere? Is it in a different place (not in the apk) entirely?
> 
> Unrelated... What in the world is Pop Jam/spacepop...? And why is it in the assets folder?

Android's Data.rsdk is actually called patch[...].obb. You have to either get the xapk file of the game or have a rooted android phone and find the obb files there. There is always a main[...].obb and a patch[...].obb contained within the xapk, the main is actually a zip archive with the mp4 video files and the patch is the Data.rsdk you're looking for, you'll just have to rename it

**Comment by lividhen** [comment]
OH! Its lucky I already use root access frequently 😂! Ill try that! Thank you!

**Comment by Tyberkid967** [comment]
I Didnt need root access to get the obb files. All i did was start the game at least once and then it was in the obb folder in the android folder

**Comment by parkerlreed** [comment]
The root is needed it on Android 11+ (scoped storage blocks non root from seeing Android/data)

**Comment by Glaceon575** [comment]
You can use an app cloning tool to get all of the files, if you can get it to give you the apk. This is the method I used to extract the data. You can just unzip the apk. This might also work on Android 11.

**Comment by cicinwad** [comment]
I will try extracting data rsdk without root

**Comment by cicinwad** [comment]
But how did there’s a way to extract an patch obb without root?!, on android

**Comment by Davedson-debug** [comment]
ugh, help? how to get the Data.rsdk if the patch obb file simply doesn't work? the obb with videos works normally as it should, but the one with Data.rsdk just doesn't work no matter what i do, tried several archive managers (RAR, 7Zip, etc etc), and even sites like extract.me, but to no avail, all i get is an error that the file is either corrupted/broken or might not even be an archive file altogether

**Comment by cicinwad** [comment]
Then use rsdk unpack anyway for pc.

**Comment by lividhen** [comment]
> ugh, help? how to get the Data.rsdk if the patch obb file simply doesn't work? the obb with videos works normally as it should, but the one with Data.rsdk just doesn't work no matter what i do, tried several archive managers (RAR, 7Zip, etc etc), and even sites like extract.me, but to no avail, all i get is an error that the file is either corrupted/broken or might not even be an archive file altogether

It is a non standard archive containing all the game assets. There should be no need to extract it.

**Comment by Davedson-debug** [comment]
i need to extract the obb containing Data.rsdk, not the Data.rsdk itself, i even checked the patch obb in HxD and it's just garbage/machine code, while the obb with videos actually has filenames when put into HxD, is the patch obb encrypted?

**Comment by Davedson-debug** [comment]
![image](https://user-images.githubusercontent.com/79422339/158081436-ee304fdf-2776-4c33-baed-9f3da864b3d5.png)

it simply refuses to open no matter what i do, so i'm probably not going to play it anytime soon

**Comment by Davedson-debug** [comment]
fucking pardon me, the patch obb is the Data.rsdk itself???? i hope that the person who thought that this was a good idea gets castrated for it, i understood that only after reading the answer like 5 times due to confusing choice of words

**Comment by MegAmi24** [comment]
dude calm down

**Comment by NicholasPeet** [comment]
> dude calm down

of anything this helped me the most, strait top the point

**Comment by OisinCitywise** [comment]
> ugh, help? how to get the Data.rsdk if the patch obb file simply doesn't work? the obb with videos works normally as it should, but the one with Data.rsdk just doesn't work no matter what i do, tried several archive managers (RAR, 7Zip, etc etc), and even sites like extract.me, but to no avail, all i get is an error that the file is either corrupted/broken or might not even be an archive file altogether



> fucking pardon me, the patch obb is the Data.rsdk itself???? i hope that the person who thought that this was a good idea gets castrated for it, i understood that only after reading the answer like 5 times due to confusing choice of words

It probably wasn't anyone's fault for the files name to be different. it probably was the APK packager at fault there.

**Comment by MegAmi24** [comment]
> It probably wasn't anyone's fault for the files name to be different. it probably was the APK packager at fault there.

Nope, that's just how the file is named. It's like that regardless of the APK packer you use.

**Comment by Davedson-debug** [comment]
> 

This, literally this, APK packer used give no difference whatsoever in file names, and even then i just WinRar

**Comment by Microphone143** [comment]
I'm trying to figure out how to get the data.rsdk from the apks even though I've already got it I'm just trying to make it stop file more accessible for legal means because I can't just share a download link to everyone to get the data.rsdk so can anyone figure out where the data that rsdk is inside the APK and this is the Sega forever version we're talking about not the version you get if you pay to remove the ads
