### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by IacobusKopiirefuto** [Rubberduckycooly/Sonic-CD-11-Decompilation#77]
I have found your project in this list <https://luxtorpeda-dev.github.io/packages.html> of game engines, where license for your project is listed as "Unknown". As you can see in the list, there are many reverse engineering projects of similar nature, yet they can share code under clear libre/open source license.

Could you pick a license or at least at give some information about the copyright status in your README.md file?

If you want more information about different licenses, GitHub has a site that can help you with that <https://choosealicense.com/>. This site has also info on what does it mean, when repository does not have a license <https://choosealicense.com/no-permission/>.

If you need some inspiration on how to apply licensing on reverse engineering projects, you might find this [copyright page](https://asahilinux.org/copyright/) of Asahi Linux helpful. This project tries to reverse engineer hardware of M1 Mac Mini, so GNU/Linux can run on it.

**Comment by cheatfreak47** [comment]
this was already discussed for Sonic 1/2 and it was decided to have them left unlicensed and provided as is.

**Comment by IacobusKopiirefuto** [comment]
Thank you for answer. If I have any further comments I will direct them to the Sonic 1/2 issue that you have provided.

**Comment by Clownacy** [comment]
Update: 517e07fea6fba7602c20b05ebfa682cedd1b353c added The Unlicense, and  #102 wants to switch to GPLv3+.

`Audio.cpp` has a fair bit of code from me in it, so licensing it without asking me first seems a little rude.

**Comment by cheatfreak47** [comment]
Yeah, I agree, it was better to just leave the license up in the air permanently.

**Comment by Clownacy** [comment]
The license has now been changed to a custom non-commercial one in 5721045adf23cb5ec6b747b9ed29e7fd26536846
