### ISSUE TITLE
[FEATURE REQUEST] FLAC audio support.

### ISSUE THREAD

**Issue by Hydra-Spectre** [Rubberduckycooly/Sonic-CD-11-Decompilation#78]
Unfortunately, the music in Sonic CD 2011 is compressed to Vorbis and it doesn't sound as clean as the uncompressed CD audio on the Sonic Gems Collection version, the Windows 95 version and the Sega CD version.
Having the option for a FLAC soundtrack can fix this.

**Comment by Rubberduckycooly** [comment]
the original games did not use FLAC, they only used vorbis for music, so we will not be adding FLAC as a supported file format, you or anyone else is welcome to make a branch and add FLAC support, it just wont be in master for the sake of preservation of the original codebase

**Comment by Clownacy** [comment]
Not to be an ass, but I didn't think this project was concerned with preservation, since it migrates the entire engine to SDL2 and has features backported from later RSDK versions.
