### ISSUE TITLE
Steam / Audio/Video Off-Sync

### ISSUE THREAD

**Issue by AskaLangly** [Rubberduckycooly/Sonic-CD-11-Decompilation#79]
Reproduce: Set game to use US soundtrack, start new Sonic file.
Theme starts somewhat later than video. Audio cuts early when done.

**Comment by Clownacy** [comment]
According to  #61, this is an issue with the video file itself. Can you check if that's true in your case as well?

**Comment by Leonx254** [comment]
This is a problem of the video file indeed, nothing that can be done here
