### ISSUE TITLE
Hiding the cursor

### ISSUE THREAD

**Issue by vanfanel** [Rubberduckycooly/Sonic-CD-11-Decompilation#83]
Hi!

Adding `SDL_ShowCursor(SDL_FALSE);` before calling SDL_CreateWindow() in SonicCDDecomp/Drawing.cpp hides the cursor with no problems on my builds.

Can you hide the cursor by default (or maybe should I do a PR)?

Thanks!

**Comment by Adamillo** [comment]
I think you should rather make a PR for this instead of opening an issue

**Comment by vanfanel** [comment]
@Adamillo Ok, there it is: https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/pull/91

**Comment by Rubberduckycooly** [comment]
added automatic mouse hiding after 2 seconds of inactivity from mouse
