### ISSUE TITLE
Wrongly showing touch screen buttons in special stage on PC version

### ISSUE THREAD

**Issue by jp438-2** [Rubberduckycooly/Sonic-CD-11-Decompilation#85]
When using the lastest data.rsdk version (extracted and renamed from the Sega Forever mobile version) touch screen buttons (the D-Pad, A Button and Pause) are shown on special stages with a purple hue despite playing on PC. They are not visible when playing the main levels. Screenshot below.

![Screenshot 2021-02-08 14 12 07](https://user-images.githubusercontent.com/1391140/107231645-746d1f80-6a18-11eb-99b9-c4422cdabfe4.png)

**Comment by vaguerant** [comment]
What version are you using? I believe this is already fixed in the current codebase, but possibly not in release versions yet.

**Comment by jp438-2** [comment]
I'm using the latest release version (v1.1.0). I guess I can either wait for the next release or compile it myself then. Thanks for the quick reply!

**Comment by Piccadili-Hill** [comment]
> I'm using the latest release version (v1.1.0). I guess I can either wait for the next release or compile it myself then. Thanks for the quick reply!

No in fact you have to do it yourself.

Step 1: Go to the sprites folder look for the Dpad icone (don't forget the Dpad icone for the special stage)
Step 2: Color them in purple with gimp

**Comment by Rubberduckycooly** [comment]
this is known to happen with the mobile data.rsdk files
the latest version will have `DisableTouchControls=true/false` in the settings.ini file, set it to true to hide the touch controls if you're using mobile vers
