### ISSUE TITLE
Android versions

### ISSUE THREAD

**Issue by xcom169** [Rubberduckycooly/Sonic-CD-11-Decompilation#87]
Hello All!

The data.rsdk  can be obtained from the Android apk file ?  
From which directory it can be copied?

**Comment by xcom169** [comment]
I see now that the data.rsdk can be only obtained from the PC version.

**Comment by dilworks** [comment]
As Sega changed stuff on the Sega Forever version (the only one you can get nowadays on Android devices) of Sonic CD, pulling the Data.rsdk is no longer straightforward, so these are your options:

- Root your phone (if you have that option, that is!)
- Buy the game on the Amazon store (at some point they even gave it for free if you had an Amazon smartdevice!): https://www.amazon.com/Sega-of-America-Sonic-CD/dp/B008K9UZY4/ - on those, you can simply pull the APK out of your device with any half-decent file manager (I used Total Commander on an ancient Amazon Kindle Fire) - the Data.rsdk is there (although I haven't tested it as I also own the PC version)

**Comment by vaguerant** [comment]
You don't need a rooted Android device to obtain the mobile `Data.rsdk` from Sega Forever versions. It can be found in the directory `Android/obb/com.sega.soniccd.classic`. The filename of the `Data.rsdk` file is `patch.*.com.sega.soniccd.classic.obb`. The `*` is a number which varies based on the version of the game you have downloaded. You can simply rename this file to `Data.rsdk` to use it with the decomp.

**Comment by xcom169** [comment]
Ok, Thanks!
