### ISSUE TITLE
Compiling issue with latest version

### ISSUE THREAD

**Issue by coreybruce** [Rubberduckycooly/Sonic-CD-11-Decompilation#89]
Hey there I pulled the latest version of Sonic-CD-11-Decompilation on Linux but when I go to compile using make I get a erro saying it's missing a file 

```
[corey@manjaro-pi Sonic-CD-11-Decompilation]$ make -j4
mkdir -p objects/SonicCDDecomp
g++ -MMD -MP -MF objects/SonicCDDecomp/Userdata.cpp.d -I/usr/include/SDL2 -D_REENTRANT  -Idependencies/all/theoraplay  SonicCDDecomp/Userdata.cpp -o objects/SonicCDDecomp/Userdata.cpp.o -c
SonicCDDecomp/Userdata.cpp:614:10: fatal error: ghc/filesystem.hpp: No such file or directory
  614 | #include <ghc/filesystem.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:50: objects/SonicCDDecomp/Userdata.cpp.o] Error 1
```

Would this be a bug or should I do a clean clone?

**Comment by coreybruce** [comment]
I can see the file is there in ```/dependencies/all/filesystem/include/ghc/``` but it seems to not be able to find it for some odd reason.

**Comment by bslenul** [comment]
Tried to compile it today and had the same issue, I just replaced the line `#include <ghc/filesystem.hpp>` with `#include "../dependencies/all/filesystem/include/ghc/filesystem.hpp"` and it worked fine.

**Comment by coreybruce** [comment]
Looks like the make file was also updated and fixed this issue. :D
