### ISSUE TITLE
Possible Sonic Mania 3DS Port

### ISSUE THREAD

**Issue by obscurerev** [Rubberduckycooly/Sonic-CD-11-Decompilation#99]
With this new code, could it be possible to port Sonic Mania to the 3DS?

**Comment by JoeWeigmanVideo** [comment]
A 3Ds port of mania would probably require a decompilation of RSDKv5, which has been stated multiple times that one will not be happening from anyone associated with this project at least. This also isn't the place to ask about mania especially as an Issue, RSDKv3 and v5 are very different and aren't really comparable.

**Comment by Rubberduckycooly** [comment]
Sonic cd was made in Retro Engine v3, s1/S2 were made in Retro Engine v4 and mania was made in v5, decompiling sonic mania would take a huge amount of effort and will not happen for at LEAST 5 years, and cannot be done with this current code, partial recreations or ports can be made from specific aspects but the entire game cannot be ported
